// Auto-generated by extract_clips.py
export const CLIP_PATHS = [
  "/assets/clips/action_1.webp",
  "/assets/clips/domain_open.webp",
  "/assets/clips/domain_peak.webp",
  "/assets/clips/domain_close.webp"
];
